In [ ]:
#Letter recognition using Holand-style

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import train_test_split

In [25]:
data=pd.read_csv('letterdata.csv')

In [26]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [27]:
data.shape

(20000, 17)

In [28]:
data.isnull().values.any()

np.False_

In [29]:
data.head()

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10

In [30]:
x=np.array(data)[:,1:16]
y=np.array(data.letter)[:]

In [31]:
print(x)

[[2 8 3 ... 0 8 0]
 [5 12 3 ... 2 8 4]
 [4 11 6 ... 3 7 3]
 ...
 [6 9 6 ... 2 12 2]
 [2 3 4 ... 1 9 5]
 [4 9 6 ... 2 7 2]]


In [32]:
x_train=x[:16000,:]
x_test=x[16001:,:]
y_train=y[:16000]
y_test=y[16001:]

In [34]:
model=svm.SVC(C=3)

In [36]:
#C is penalty for missclassification
model.fit(x_train,y_train)

SVC(C=3)

In [37]:
predict=model.predict(x_test)

In [1]:
from sklearn import metrics
print("Confusion matrix")
c=metrics.confusion_matrix(x_test,predict,labels=[0,1])

Confusion matrix


NameError: name 'x_test' is not defined